version: "3.9"

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wineprediction
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 10s
      retries: 10

  backend:
    build:
      context: ./winepredictiveBack
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/wineprediction?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_HOST: db
      SPRING_DATASOURCE_PORT: 3306
    ports:
      - "8081:8081"

  frontend:
    build:
      context: ./winepredictiveFront
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "4200:80"

  cypress:
    image: cypress/included:12.17.0
    container_name: wine_cypress
    working_dir: /e2e
    volumes:
      - ./cypressPredictiveSystem:/e2e
    environment:
      - CYPRESS_baseUrl=http://frontend
    profiles: ["e2e"]
    entrypoint: ["tail", "-f", "/dev/null"]

  jenkins:
    image: jenkins/jenkins:lts
    container_name: predictivesystem-jenkins
    privileged: true
    user: root
    restart: unless-stopped
    ports:
      - "8085:8080"
      - "50000:50000"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - jenkins_home:/var/jenkins_home        # workspace y configuraciones persistentes
      - /var/run/docker.sock:/var/run/docker.sock  # permite ejecutar docker dentro de Jenkins

volumes:
  mysql_data:
  jenkins_home:
