spring.application.name=winepredictive
# Configuraci�n de la URL de la base de datos
#spring.datasource.url=jdbc:mysql://localhost:3306/wineprediction?zeroDateTimeBehavior=convertToNull
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://db:3306/wineprediction?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}

# Credenciales de la base de datos
#spring.datasource.username=root
#spring.datasource.password=
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.profiles.active=dev

# Driver JDBC para MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuraci�n de Hibernate (ORM)
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Configuraci�n de tiempo de espera
spring.datasource.hikari.connection-timeout=2000000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.maximum-pool-size=10

#Puerto de servicio
server.port=8081
server.address=0.0.0.0

server.tomcat.uri-encoding=UTF-8

#LLama settings
#spring.ai.ollama.base-url=http://localhost:1134
#spring.ai.ollama.chat.options.model=llama3.2
#spring.ai.ollama.chat.options.temperature=0.4

#Gemini IA
spring.ai.openai.chat.base-url=https://generativelanguage.googleapis.com
spring.ai.openai.chat.completions-path=/v1beta/openai/chat/completions
spring.ai.openai.api-key=AIzaSyBuR5ytQiQ3bkcMruX_-UXnFrP4q1x1n0M
spring.ai.openai.chat.options.model=gemini-2.0-flash



